server:
  port: 8080

spring:
  application:
    name: blog-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 1.15.64.53:8848
    gateway:
      routes:
        - id: blog-user
          uri: lb://blog-user
          predicates:
            - Path=/api/v1/user/**
          filters:
            - StripPrefix=3
